### ISSUE TITLE
Trouble using multiple .osm files in splitter

### ISSUE THREAD

**Issue by ravenfeld** [roelderickx/contour-osm#2]
Hello,

I don't think the problem is related to your code but I don't know where to find the information.
If I have a .shp file that I convert to .shp and use splitter (https://www.mkgmap.org.uk/doc/splitter.html) then mkgmap (https://www.mkgmap.org.uk/doc/index.html) everything works fine.
But as soon as I convert several .shp files to .osm and use splitter in a command line with *.osm, I get this problem 

<img width="818" alt="Capture d’écran 2023-11-28 à 23 57 09" src="https://github.com/roelderickx/contour-osm/assets/3765114/c9d3c7b1-444e-4ee9-8bfe-e8c0b8006e01">

If I have x .osm files and run splitter x times, I have no problem.

I didn't forget to add --add-bounds in the generation of osm files for your information.
I think there must be a difference in the .osm files compared to https://github.com/agrenott/pyhgtmap because I don't have this problem with the x files made by pyhgtmap.

If you have a idea, I'd love to hear from you. If not, I'll try to make a splitter loop script.

Thank you in advance and sorry for going off topic.

**Comment by roelderickx** [comment]
Hello @ravenfeld,

It looks like the shapefile contains polygons which are translated by ogr2osm to relations (which will be closed by a line from start to end by mkgmap), while pyhgtmap creates ways (which are not closed). But that is just an assumption.

But then the question remains how to solve it. It is indeed not something which can be done with ogr2osm or contour-osm. Maybe have a look at the `--keep-complete=false` of the splitter application? It seems to be related.

A splitter loop script is not that hard either. In bash you can do something like this (untested):
```
for X in *.osm
do
    java -Xmx2000m -jar splitter.jar $X
done
```

**Comment by ravenfeld** [comment]
Thank you very much, but I don't understand why executing via a for works?
But yes, that's what I've done for the moment. It's less "pretty" because I have to calculate the next index, but it works.

**Comment by roelderickx** [comment]
> Thank you very much, but I don't understand why executing via a for works?

Ah ok, I think I start understanding...

Ogr2osm generates nodes, ways and relations with id's starting at -1. If you convert multiple shapefiles independently they will all contain nodes, ways or relations with the same id's. The splitter application considers them as 1 object and connects them.

That's in fact correct behaviour, but ogr2osm can deal with this issue. All you need to do is pass the `--idfile` and `--saveid` parameters to save the last id to a file and continue with the next id for the next shapefile.

**Comment by ravenfeld** [comment]
Okay, I'm going to go all the way with the splitter loop technique because I still don't know if it's a good idea what I'm doing.
Because if the file for France goes from 2GB to 8GB, it's useless. 
In any case, I'm testing on a small region and the rendering is nice compared to hgt.

Thank you very much for your time. 
Did you render for Garmin devices given your scripts no?

**Comment by roelderickx** [comment]
Yes idd I used it for the same use-case on a Garmin device. Only for limited regions though, just the part where I wanted to hike, and with better data than the SRTM to maximize the quality of the elevation lines.
Also, I started by importing the elevation lines in a database because I wanted to render the maps on paper as well, so I didn't have multiple osm files. But I don't recommend that in your case, it is overkill.

**Comment by ravenfeld** [comment]
Ok
When you talk about better data. Was it global data or like for me linked to a country?

I saw this while searching https://data.maptiler.com/downloads/dataset/contours/#16.7/45.240348/5.726228
but I haven't looked yet to see if the format it gives can be used.

**Comment by roelderickx** [comment]
No it was never global data, the resolution of local data linked to a country's geographical institute is always better.
That being said, it was always a non-obvious task to convert the raster data to contour lines using GDAL. It is hard to explain how to do it as it is different for every country. If you can find ready to use contour files I'd suggest using them in stead.
As for the datasource you mentioned: I am not sure if MBTiles will help you, ogr2osm cannot work with them. So the question is if you can convert it somehow. I suggest starting with [a small country](https://data.maptiler.com/downloads/dataset/contours/europe/luxembourg/#8.25/49.817/6.133) to see if it works for you.

**Comment by ravenfeld** [comment]
Thanks a lot gdal memory it's processed, I had it used to make a mbtiles to pbf but a few years ago.
Anyway for now I'm concentrating on France with IGN data and I'll see later for other countries. 
In any case, it's a very complex field.

**Comment by ravenfeld** [comment]
For the record, my new file is almost the same size as before.
So, for the moment, it's a great success.
But I'm going to have to maintain 2 files for France for cross-border commuters.

thank you very much for your help
